apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-petclinic-data-jdbc.fullname" . }}-deployment
  labels:
    {{- include "spring-petclinic-data-jdbc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spring-petclinic-data-jdbc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spring-petclinic-data-jdbc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring-petclinic-data-jdbc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{- if .Values.otel.enabled }}
        - name: otel-install
          image: curlimages/curl
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          args:
            - "-L"
            - "https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/{{ .Values.otel.version }}/opentelemetry-javaagent.jar"
            - "-o"
            - "/opt/monitoring/opentelemetry-javaagent.jar"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- with .Values.livenessProbe }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
          readinessProbe:
            {{- with .Values.readinessProbe }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: "{{ tpl $key $ }}"
              value: "{{ tpl $value $ }}"
            {{- end }}
          {{- end }}
          {{- if .Values.otel.enabled }}
            {{- range $key, $value := .Values.otel.env }}
            - name: "{{ tpl $key $ }}"
              value: "{{ tpl $value $ }}"
            {{- end }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- tpl . $ | nindent 12 }}
              {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- tpl . $ | nindent 12 }}
              {{- end }}
              {{- if .Values.PersistentVolumeClaim.enabled }}
              - name: {{ include "spring-petclinic-data-jdbc.fullname" . }}-volume
                mountPath: {{ .Values.PersistentVolumeClaim.mountPath }}
              {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.extraVolumes }}
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- if .Values.PersistentVolumeClaim.enabled }}
        - name: {{ include "spring-petclinic-data-jdbc.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "spring-petclinic-data-jdbc.fullname" . }}-pvc
      {{- end }}