{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spring-petclinic-data-jdbc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
  {{- include "spring-petclinic-data-jdbc.selectorLabels" . | nindent 6 }}
  {{- with .Values.podDisruptionBudget }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
