apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-petclinic-data-jdbc.fullname" . }}
  labels:
    {{- include "spring-petclinic-data-jdbc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "spring-petclinic-data-jdbc.selectorLabels" . | nindent 4 }}
