name: Test on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'espresso'
          cache: 'gradle'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests with coverage
        run: ./app/spring-petclinic-data-jdbc/gradlew clean test jacocoTestReport


      # TODO jacocoTestReport 파일 업로드 구현
      #- name: Upload coverage to Something
      #  env:
      #    file: ./app/spring-petclinic-data-jdbc/build/reports/tests/test/index.html

      - name: Build test
        run: ./gradlew build

      # TODO Send Success messages
      #- name: Upload coverage to Something
      #  env:
      #    token: ${{ secrets.MESSAGE_TOKEN }}
      #    jacocoURl:
      #  run: |
